# Generated by Django 4.0.5 on 2022-06-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('ISSUED', 'ISSUED'), ('PAID', 'PAID')], max_length=10)),
                ('dueDate', models.DateField(auto_now=True)),
                ('customerName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('metric', models.CharField(choices=[('KILOGRAM', 'KILOGRAM'), ('LITER', 'LITER'), ('PACKET', 'PACKET'), ('PIECE', 'PIECE')], max_length=10)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('invoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.product')),
            ],
        ),
    ]
