# Generated by Django 4.0.5 on 2022-06-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='invoiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice', to='invoice.product'),
        ),
    ]
