# Generated by Django 4.0.5 on 2022-06-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoiceproduct_invoiceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customerAddress',
            field=models.CharField(default='H-24, K Vihar, Janakpuri East, New Delhi, 110052', max_length=200),
        ),
    ]
